# Generated by Django 4.0.3 on 2022-03-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='Details',
        ),
    ]
