# Generated by Django 4.0.3 on 2022-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_rename_post_image_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
