# Generated by Django 4.0.3 on 2022-03-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
    ]
